import { toISODate } from './date'
import type { Job, Machine } from './types'

export const machines: Machine[] = [
  { id: 'm1', name: 'Laser Cutter A', type: 'Laser Cutter', status: 'Running' },
  { id: 'm2', name: 'CNC Mill 1', type: 'CNC Mill', status: 'Running' },
  { id: 'm3', name: 'CNC Mill 2', type: 'CNC Mill', status: 'Idle' },
  { id: 'm4', name: 'Injection Press A', type: 'Injection Press', status: 'Maintenance' },
  { id: 'm5', name: 'Assembly Line 1', type: 'Assembly Line', status: 'Running' },
  { id: 'm6', name: 'Paint Booth A', type: 'Paint Booth', status: 'Idle' },
]

function offset(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return toISODate(d)
}

export const jobs: Job[] = [
  {
    id: 'JOB-1001',
    productName: 'Aluminum Bracket Set',
    customerName: 'Northline Manufacturing',
    quantity: 500,
    dueDate: offset(0),
    status: 'In Progress',
    machineId: 'm2',
    notes: [{ id: 'n1', text: 'Customer confirmed spec revision.', createdAt: offset(-2) }],
    createdAt: offset(-5),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1002',
    productName: 'Precision Steel Hinge',
    customerName: 'Ardent Fabrication',
    quantity: 1200,
    dueDate: offset(0),
    status: 'Pending',
    machineId: 'm3',
    notes: [],
    createdAt: offset(-3),
    updatedAt: offset(-3),
  },
  {
    id: 'JOB-1003',
    productName: 'Custom Extruded Aluminum Heat Sink Enclosure Panel',
    customerName: 'Vertex Robotics',
    quantity: 80,
    dueDate: offset(1),
    status: 'In Progress',
    machineId: 'm1',
    notes: [{ id: 'n2', text: 'Awaiting material delivery.', createdAt: offset(-1) }],
    createdAt: offset(-6),
    updatedAt: offset(0),
  },
  {
    id: 'JOB-1004',
    productName: 'Polymer Gear Housing',
    customerName: 'Meridian Auto Parts',
    quantity: 300,
    dueDate: offset(-3),
    status: 'Delayed',
    machineId: 'm4',
    notes: [
      { id: 'n3', text: 'Press down for scheduled maintenance.', createdAt: offset(-4) },
      { id: 'n4', text: 'Rescheduled to next slot.', createdAt: offset(-2) },
    ],
    createdAt: offset(-10),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1005',
    productName: 'Stainless Steel Bracket',
    customerName: 'Northline Manufacturing',
    quantity: 150,
    dueDate: offset(-1),
    status: 'Delayed',
    machineId: 'm2',
    notes: [{ id: 'n5', text: 'Operator reported tooling issue.', createdAt: offset(-1) }],
    createdAt: offset(-8),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1006',
    productName: 'Molded Cable Clip',
    customerName: 'Brightline Electronics',
    quantity: 5000,
    dueDate: offset(5),
    status: 'Pending',
    machineId: 'm4',
    notes: [],
    createdAt: offset(-1),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1007',
    productName: 'Anodized Enclosure Lid',
    customerName: 'Vertex Robotics',
    quantity: 220,
    dueDate: offset(2),
    status: 'In Progress',
    machineId: 'm1',
    notes: [{ id: 'n6', text: 'First article approved.', createdAt: offset(-3) }],
    createdAt: offset(-7),
    updatedAt: offset(-3),
  },
  {
    id: 'JOB-1008',
    productName: 'Welded Frame Assembly',
    customerName: 'Ardent Fabrication',
    quantity: 60,
    dueDate: offset(-2),
    status: 'Completed',
    machineId: 'm5',
    notes: [{ id: 'n7', text: 'Shipped ahead of revised schedule.', createdAt: offset(-2) }],
    createdAt: offset(-12),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1009',
    productName: 'Rubber Gasket Sheet',
    customerName: 'Meridian Auto Parts',
    quantity: 900,
    dueDate: offset(7),
    status: 'Pending',
    machineId: 'm4',
    notes: [],
    createdAt: offset(-1),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1010',
    productName: 'Machined Pump Housing',
    customerName: 'Coastal Hydraulics',
    quantity: 40,
    dueDate: offset(3),
    status: 'In Progress',
    machineId: 'm3',
    notes: [{ id: 'n8', text: 'Tolerance check scheduled.', createdAt: offset(-1) }],
    createdAt: offset(-4),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1011',
    productName: 'Powder Coated Panel',
    customerName: 'Brightline Electronics',
    quantity: 180,
    dueDate: offset(-5),
    status: 'Completed',
    machineId: 'm6',
    notes: [],
    createdAt: offset(-15),
    updatedAt: offset(-5),
  },
  {
    id: 'JOB-1012',
    productName: 'Sheet Metal Bracket',
    customerName: 'Northline Manufacturing',
    quantity: 750,
    dueDate: offset(0),
    status: 'Delayed',
    machineId: 'm1',
    notes: [{ id: 'n9', text: 'Laser cutter recalibration in progress.', createdAt: offset(0) }],
    createdAt: offset(-6),
    updatedAt: offset(0),
  },
  {
    id: 'JOB-1013',
    productName: 'Injection Molded Clip',
    customerName: 'Coastal Hydraulics',
    quantity: 3000,
    dueDate: offset(4),
    status: 'Pending',
    machineId: 'm4',
    notes: [],
    createdAt: offset(-2),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1014',
    productName: 'Aluminum Heat Shield',
    customerName: 'Vertex Robotics',
    quantity: 130,
    dueDate: offset(6),
    status: 'In Progress',
    machineId: 'm2',
    notes: [{ id: 'n10', text: 'Second shift assigned.', createdAt: offset(-1) }],
    createdAt: offset(-5),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1015',
    productName: 'Welded Support Bracket',
    customerName: 'Ardent Fabrication',
    quantity: 95,
    dueDate: offset(-4),
    status: 'Completed',
    machineId: 'm5',
    notes: [{ id: 'n11', text: 'Passed final inspection.', createdAt: offset(-4) }],
    createdAt: offset(-14),
    updatedAt: offset(-4),
  },
  {
    id: 'JOB-1016',
    productName: 'Painted Trim Panel',
    customerName: 'Meridian Auto Parts',
    quantity: 260,
    dueDate: offset(2),
    status: 'Pending',
    machineId: 'm6',
    notes: [],
    createdAt: offset(-3),
    updatedAt: offset(-3),
  },
  {
    id: 'JOB-1017',
    productName: 'CNC Machined Spindle',
    customerName: 'Coastal Hydraulics',
    quantity: 25,
    dueDate: offset(8),
    status: 'In Progress',
    machineId: 'm3',
    notes: [{ id: 'n12', text: 'Long lead time on raw stock.', createdAt: offset(-5) }],
    createdAt: offset(-9),
    updatedAt: offset(-5),
  },
  {
    id: 'JOB-1018',
    productName: 'Extruded Rail Segment',
    customerName: 'Brightline Electronics',
    quantity: 400,
    dueDate: offset(-1),
    status: 'Delayed',
    machineId: 'm2',
    notes: [{ id: 'n13', text: 'Waiting on customer sign-off.', createdAt: offset(-1) }],
    createdAt: offset(-7),
    updatedAt: offset(-1),
  },
]
