import { toISODate } from './date'
import type { Job, Machine } from './types'

export const machines: Machine[] = [
  { id: 'm1', name: 'Laser Cutter A', type: 'Laser Cutter', status: 'Running' },
  { id: 'm2', name: 'CNC Mill 1', type: 'CNC Mill', status: 'Running' },
  { id: 'm3', name: 'CNC Mill 2', type: 'CNC Mill', status: 'Idle' },
  { id: 'm4', name: 'Injection Press A', type: 'Injection Press', status: 'Maintenance' },
  { id: 'm5', name: 'Assembly Line 1', type: 'Assembly Line', status: 'Running' },
  { id: 'm6', name: 'Paint Booth A', type: 'Paint Booth', status: 'Idle' },
]

function offset(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return toISODate(d)
}

export const jobs: Job[] = [
  {
    id: 'JOB-1001',
    productName: 'Aluminum Bracket Set',
    customerName: 'Northline Manufacturing',
    quantity: 500,
    dueDate: offset(0),
    status: 'In Progress',
    machineId: 'm2',
    notes: [{ id: 'n1', text: 'Customer confirmed spec revision.', createdAt: offset(-2) }],
    createdAt: offset(-5),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1002',
    productName: 'Precision Steel Hinge',
    customerName: 'Ardent Fabrication',
    quantity: 1200,
    dueDate: offset(0),
    status: 'Pending',
    machineId: 'm3',
    notes: [],
    createdAt: offset(-3),
    updatedAt: offset(-3),
  },
  {
    id: 'JOB-1003',
    productName: 'Custom Extruded Aluminum Heat Sink Enclosure Panel',
    customerName: 'Vertex Robotics',
    quantity: 80,
    dueDate: offset(1),
    status: 'In Progress',
    machineId: 'm1',
    notes: [{ id: 'n2', text: 'Awaiting material delivery.', createdAt: offset(-1) }],
    createdAt: offset(-6),
    updatedAt: offset(0),
  },
  {
    id: 'JOB-1004',
    productName: 'Polymer Gear Housing',
    customerName: 'Meridian Auto Parts',
    quantity: 300,
    dueDate: offset(-3),
    status: 'Delayed',
    machineId: 'm4',
    notes: [
      { id: 'n3', text: 'Press down for scheduled maintenance.', createdAt: offset(-4) },
      { id: 'n4', text: 'Rescheduled to next slot.', createdAt: offset(-2) },
    ],
    createdAt: offset(-10),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1005',
    productName: 'Stainless Steel Bracket',
    customerName: 'Northline Manufacturing',
    quantity: 150,
    dueDate: offset(-1),
    status: 'Delayed',
    machineId: 'm2',
    notes: [{ id: 'n5', text: 'Operator reported tooling issue.', createdAt: offset(-1) }],
    createdAt: offset(-8),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1006',
    productName: 'Molded Cable Clip',
    customerName: 'Brightline Electronics',
    quantity: 5000,
    dueDate: offset(5),
    status: 'Pending',
    machineId: 'm4',
    notes: [],
    createdAt: offset(-1),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1007',
    productName: 'Anodized Enclosure Lid',
    customerName: 'Vertex Robotics',
    quantity: 220,
    dueDate: offset(-2),
    status: 'In Progress',
    machineId: 'm1',
    notes: [{ id: 'n6', text: 'First article approved.', createdAt: offset(-3) }],
    createdAt: offset(-7),
    updatedAt: offset(-3),
  },
  {
    id: 'JOB-1008',
    productName: 'Welded Frame Assembly',
    customerName: 'Ardent Fabrication',
    quantity: 60,
    dueDate: offset(-2),
    status: 'Completed',
    machineId: 'm5',
    notes: [{ id: 'n7', text: 'Shipped ahead of revised schedule.', createdAt: offset(-2) }],
    createdAt: offset(-12),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1009',
    productName: 'Rubber Gasket Sheet',
    customerName: 'Meridian Auto Parts',
    quantity: 900,
    dueDate: offset(7),
    status: 'Pending',
    machineId: 'm4',
    notes: [],
    createdAt: offset(-1),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1010',
    productName: 'Machined Pump Housing',
    customerName: 'Coastal Hydraulics',
    quantity: 40,
    dueDate: offset(3),
    status: 'In Progress',
    machineId: 'm3',
    notes: [{ id: 'n8', text: 'Tolerance check scheduled.', createdAt: offset(-1) }],
    createdAt: offset(-4),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1011',
    productName: 'Powder Coated Panel',
    customerName: 'Brightline Electronics',
    quantity: 180,
    dueDate: offset(-5),
    status: 'Completed',
    machineId: 'm6',
    notes: [],
    createdAt: offset(-15),
    updatedAt: offset(-5),
  },
  {
    id: 'JOB-1012',
    productName: 'Sheet Metal Bracket',
    customerName: 'Northline Manufacturing',
    quantity: 750,
    dueDate: offset(0),
    status: 'Delayed',
    machineId: 'm1',
    notes: [{ id: 'n9', text: 'Laser cutter recalibration in progress.', createdAt: offset(0) }],
    createdAt: offset(-6),
    updatedAt: offset(0),
  },
  {
    id: 'JOB-1013',
    productName: 'Injection Molded Clip',
    customerName: 'Coastal Hydraulics',
    quantity: 3000,
    dueDate: offset(4),
    status: 'Pending',
    machineId: 'm4',
    notes: [],
    createdAt: offset(-2),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1014',
    productName: 'Aluminum Heat Shield',
    customerName: 'Vertex Robotics',
    quantity: 130,
    dueDate: offset(6),
    status: 'In Progress',
    machineId: 'm2',
    notes: [{ id: 'n10', text: 'Second shift assigned.', createdAt: offset(-1) }],
    createdAt: offset(-5),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1015',
    productName: 'Welded Support Bracket',
    customerName: 'Ardent Fabrication',
    quantity: 95,
    dueDate: offset(-4),
    status: 'Completed',
    machineId: 'm5',
    notes: [{ id: 'n11', text: 'Passed final inspection.', createdAt: offset(-4) }],
    createdAt: offset(-14),
    updatedAt: offset(-4),
  },
  {
    id: 'JOB-1016',
    productName: 'Painted Trim Panel',
    customerName: 'Meridian Auto Parts',
    quantity: 260,
    dueDate: offset(2),
    status: 'Pending',
    machineId: 'm6',
    notes: [],
    createdAt: offset(-3),
    updatedAt: offset(-3),
  },
  {
    id: 'JOB-1017',
    productName: 'CNC Machined Spindle',
    customerName: 'Coastal Hydraulics',
    quantity: 25,
    dueDate: offset(8),
    status: 'In Progress',
    machineId: 'm3',
    notes: [{ id: 'n12', text: 'Long lead time on raw stock.', createdAt: offset(-5) }],
    createdAt: offset(-9),
    updatedAt: offset(-5),
  },
  {
    id: 'JOB-1018',
    productName: 'Extruded Rail Segment',
    customerName: 'Brightline Electronics',
    quantity: 400,
    dueDate: offset(-1),
    status: 'Delayed',
    machineId: 'm2',
    notes: [{ id: 'n13', text: 'Waiting on customer sign-off.', createdAt: offset(-1) }],
    createdAt: offset(-7),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1019',
    productName: 'Hardened Drive Shaft',
    customerName: 'Coastal Hydraulics',
    quantity: 140,
    dueDate: offset(-4),
    status: 'In Progress',
    machineId: 'm3',
    notes: [{ id: 'n14', text: 'Machining tolerance rework in progress.', createdAt: offset(-2) }],
    createdAt: offset(-12),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1020',
    productName: 'Anodized Side Rail',
    customerName: 'Vertex Robotics',
    quantity: 620,
    dueDate: offset(0),
    status: 'In Progress',
    machineId: 'm1',
    notes: [],
    createdAt: offset(-4),
    updatedAt: offset(0),
  },
  {
    id: 'JOB-1021',
    productName: 'Cast Iron Flywheel',
    customerName: 'Meridian Auto Parts',
    quantity: 75,
    dueDate: offset(3),
    status: 'Pending',
    machineId: 'm4',
    notes: [],
    createdAt: offset(-2),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1022',
    productName: 'Laser Cut Gusset Plate',
    customerName: 'Northline Manufacturing',
    quantity: 2400,
    dueDate: offset(-6),
    status: 'Delayed',
    machineId: 'm1',
    notes: [
      { id: 'n15', text: 'Material shortage escalated to purchasing.', createdAt: offset(-5) },
      { id: 'n16', text: 'Partial lot released to keep the line moving.', createdAt: offset(-3) },
    ],
    createdAt: offset(-15),
    updatedAt: offset(-3),
  },
  {
    id: 'JOB-1023',
    productName: 'Powder Coated Housing',
    customerName: 'Brightline Electronics',
    quantity: 310,
    dueDate: offset(-8),
    status: 'Completed',
    machineId: 'm6',
    notes: [],
    createdAt: offset(-14),
    updatedAt: offset(-8),
  },
  {
    id: 'JOB-1024',
    productName: 'Titanium Fastener Set',
    customerName: 'Halden Aerospace',
    quantity: 5200,
    dueDate: offset(9),
    status: 'Pending',
    machineId: 'm2',
    notes: [
      { id: 'n17', text: 'Certification paperwork required before release.', createdAt: offset(-1) },
    ],
    createdAt: offset(-1),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1025',
    productName: 'Molded Cable Grommet',
    customerName: 'Orbit Medical',
    quantity: 8000,
    dueDate: offset(4),
    status: 'In Progress',
    machineId: 'm4',
    notes: [],
    createdAt: offset(-5),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1026',
    productName: 'Brushed Aluminium Faceplate',
    customerName: 'Pinewood Industrial',
    quantity: 450,
    dueDate: offset(0),
    status: 'Pending',
    machineId: 'm1',
    notes: [],
    createdAt: offset(-3),
    updatedAt: offset(-3),
  },
  {
    id: 'JOB-1027',
    productName: 'Welded Chassis Subframe',
    customerName: 'Meridian Auto Parts',
    quantity: 60,
    dueDate: offset(-2),
    status: 'Pending',
    machineId: 'm5',
    notes: [{ id: 'n18', text: 'Not yet scheduled; awaiting line capacity.', createdAt: offset(-4) }],
    createdAt: offset(-9),
    updatedAt: offset(-4),
  },
  {
    id: 'JOB-1028',
    productName: 'Precision Ground Bushing',
    customerName: 'Coastal Hydraulics',
    quantity: 1800,
    dueDate: offset(6),
    status: 'In Progress',
    machineId: 'm3',
    notes: [],
    createdAt: offset(-6),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1029',
    productName: 'Injection Moulded Clip',
    customerName: 'Orbit Medical',
    quantity: 12000,
    dueDate: offset(2),
    status: 'Delayed',
    machineId: 'm4',
    notes: [{ id: 'n19', text: 'Tooling repair in progress.', createdAt: offset(-1) }],
    createdAt: offset(-11),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1030',
    productName: 'Sheet Metal Enclosure Door',
    customerName: 'Brightline Electronics',
    quantity: 240,
    dueDate: offset(11),
    status: 'Pending',
    machineId: 'm6',
    notes: [],
    createdAt: offset(-2),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1031',
    productName: 'Hard Anodised Piston Rod Assembly for Hydraulic Cylinder',
    customerName: 'Coastal Hydraulics',
    quantity: 90,
    dueDate: offset(5),
    status: 'In Progress',
    machineId: 'm3',
    notes: [
      {
        id: 'n20',
        text: 'Customer requested an extended surface finish report.',
        createdAt: offset(-3),
      },
    ],
    createdAt: offset(-8),
    updatedAt: offset(-3),
  },
  {
    id: 'JOB-1032',
    productName: 'Stamped Mounting Bracket',
    customerName: 'Northline Manufacturing',
    quantity: 3600,
    dueDate: offset(-5),
    status: 'Completed',
    machineId: 'm1',
    notes: [],
    createdAt: offset(-13),
    updatedAt: offset(-5),
  },
  {
    id: 'JOB-1033',
    productName: 'Assembled Control Panel',
    customerName: 'Halden Aerospace',
    quantity: 45,
    dueDate: offset(7),
    status: 'Pending',
    machineId: 'm5',
    notes: [],
    createdAt: offset(-1),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1034',
    productName: 'Painted Chassis Rail',
    customerName: 'Meridian Auto Parts',
    quantity: 520,
    dueDate: offset(-1),
    status: 'Delayed',
    machineId: 'm6',
    notes: [{ id: 'n21', text: 'Paint booth backlog pushed the slot.', createdAt: offset(-1) }],
    createdAt: offset(-10),
    updatedAt: offset(-1),
  },
  {
    id: 'JOB-1035',
    productName: 'CNC Turned Coupling',
    customerName: 'Pinewood Industrial',
    quantity: 700,
    dueDate: offset(1),
    status: 'In Progress',
    machineId: 'm2',
    notes: [],
    createdAt: offset(-4),
    updatedAt: offset(0),
  },
  {
    id: 'JOB-1036',
    productName: 'Deburred Valve Body',
    customerName: 'Coastal Hydraulics',
    quantity: 260,
    dueDate: offset(-7),
    status: 'Completed',
    machineId: 'm3',
    notes: [{ id: 'n22', text: 'Final inspection passed.', createdAt: offset(-7) }],
    createdAt: offset(-16),
    updatedAt: offset(-7),
  },
  {
    id: 'JOB-1037',
    productName: 'Laminated Shim Stack',
    customerName: 'Vertex Robotics',
    quantity: 15000,
    dueDate: offset(12),
    status: 'Pending',
    machineId: 'm2',
    notes: [],
    createdAt: offset(-2),
    updatedAt: offset(-2),
  },
  {
    id: 'JOB-1038',
    productName: 'Robotic Welded Frame',
    customerName: 'Orbit Medical',
    quantity: 130,
    dueDate: offset(-3),
    status: 'In Progress',
    machineId: 'm5',
    notes: [{ id: 'n23', text: 'Fixture alignment issue under review.', createdAt: offset(-1) }],
    createdAt: offset(-9),
    updatedAt: offset(-1),
  },
]

